# Generated by Django 5.2.8 on 2025-11-08 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grup',
            name='name',
            field=models.CharField(default='Grup Nou', max_length=100),
        ),
        migrations.AddField(
            model_name='grup',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupuri', to='api.task'),
        ),
    ]
